# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Ali Gholami/Desktop/onGoing/Digital Design of Computer Systems/assignments/Assignment_4/_VHDL/pattern_verifier/pattern_verifier.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Ali Gholami/Desktop/onGoing/Digital Design of Computer Systems/assignments/Assignment_4/_VHDL/pattern_verifier/pattern_verifier.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {{C:/Users/Ali Gholami/Desktop/onGoing/Digital Design of Computer Systems/assignments/Assignment_4/_VHDL/pattern_verifier/pattern_verifier.srcs/sources_1/new/pattern_verifier.vhd}}
synth_design -top PatternVerifier -part xc7vx485tffg1157-1
write_checkpoint -noxdef PatternVerifier.dcp
catch { report_utilization -file PatternVerifier_utilization_synth.rpt -pb PatternVerifier_utilization_synth.pb }
